# Generated by Django 3.0.7 on 2021-12-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_remove_project_informacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='informacion',
            field=models.BooleanField(default=False, verbose_name='Activar mas información'),
        ),
    ]
