# Generated by Django 3.0.7 on 2021-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_project_informacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='moreinformation',
            field=models.URLField(blank=True, verbose_name='URL para más informacion'),
        ),
    ]
