# Generated by Django 3.0.7 on 2021-12-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0007_auto_20211211_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='informacion',
        ),
        migrations.AlterField(
            model_name='project',
            name='moreinformation',
            field=models.URLField(blank=True, help_text='Ingrese el URL', null=True, verbose_name='URL para más informacion'),
        ),
    ]
