# Generated by Django 3.0.7 on 2021-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0009_remove_project_moreinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='moreinformation',
            field=models.URLField(blank=True, help_text='Ingrese el URL', null=True, verbose_name='URL para más informacion'),
        ),
    ]
